### ISSUE TITLE
Running the maven jib to build the container fails for me

### ISSUE THREAD

**Issue by mwalzer** [nilshoffmann/jmzqc-usecase#1]
```
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:06 min
[INFO] Finished at: 2023-02-27T09:59:50Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.3.0:dockerBuild (default-cli) on project jmzqc-usecase: Obtaining project build output files failed; make sure you have compiled your project before trying to build the image. (Did you accidentally run "mvn clean jib:build" instead of "mvn clean compile jib:build"?): /home/walzer/psi/mzqclib-manuscript/jmzqc-usecase/target/classes -> [Help 1]
```

**Comment by mwalzer** [comment]
I can't really make much of the error trace but the last line of the full debug log is 
`Caused by: java.nio.file.NoSuchFileException: /home/walzer/psi/mzqclib-manuscript/jmzqc-usecase/target/classes
`

**Comment by mwalzer** [comment]
Is there maybe something that I have to add manually before the build that hasn't been added to the repo yet?
Using main branch @ 86243bb

**Comment by nilshoffmann** [comment]
Please launch the build with:

./mvnw jib:dockerBuild

If that does not work, please try to run 

./mvnw package jib:dockerBuild

Please see the current maven workflow for more informations:

https://github.com/nilshoffmann/jmzqc-usecase/blob/main/.github/workflows/maven.yml

**Comment by mwalzer** [comment]
> ./mvnw jib:dockerBuild

That was the command that produced the above error. Result of adding `package` is just the same.

> https://github.com/nilshoffmann/jmzqc-usecase/blob/main/.github/workflows/maven.yml

But this works: ./mvnw -B jib:dockerBuild --file pom.xml  :relieved:

**Comment by nilshoffmann** [comment]
@mwalzer please check, build should work now
