### ISSUE TITLE
total ion current values

### ISSUE THREAD

**Issue by mwalzer** [nilshoffmann/jmzqc-usecase#3]
Hopefully a quick fix:
Could you fix the values for the total ion current? With `MS:4000104` as metric.
https://github.com/nilshoffmann/jmzqc-usecase/blob/0683edcb44a4c574a7d3da8e5ca2cec606b6e37a/src/main/java/org/lifstools/jmzqc/usecase/ProteomicsDDAMs1QC.java#L74-L76

**Comment by mwalzer** [comment]
Term def. for convenience
```
[Term]
id: MS:4000104
name: total ion currents
def: "Tabular representation of the total ion current detected in each of a series of mass spectra." [PSI:MS]
is_a: MS:4000005 ! table
is_a: MS:1000235 ! total ion current chromatogram
relationship: has_metric_category MS:4000009 ! ID free metric
relationship: has_metric_category MS:4000012 ! single run based metric
relationship: has_metric_category MS:4000016 ! retention time metric
relationship: has_column MS:1000767 ! native spectrum identifier format
relationship: has_optional_column MS:1000894 ! retention time
relationship: has_optional_column MS:1003059 ! number of peaks
relationship: has_column MS:1000285 ! total ion current
```

**Comment by mwalzer** [comment]
Now only missing is  `null`  -> the actual TIC values in `has_optional_column MS:1000894 ! retention time` and the native id as `has_column MS:1000767 ! native spectrum identifier format` (spectrum number would suffice for the demo use-case)

**Comment by nilshoffmann** [comment]
@mwalzer I think I fixed this in the meantime. Could you have a second look, please?
